### ISSUE TITLE
packagesIds retorna un arreglo vacio

### ISSUE THREAD

**Issue by agares29** [phpcfdi/sat-ws-descarga-masiva#12]
Estoy realizando una integración en un proyecto con Laravel, estoy siguiento el ejemplo que viene en la pagína pero al llegar a esta línea:

`$packageId = $verify->getPackagesIds()[0];`

Manda este error:

`Undefined offset: 0`

Imprimí la variable $verify y marca packagesIds como un arreglo vació y numberCfdis como 0,pero el rango de fechas que estoy seleccionando si tiene CFDIs.

¿Alguna idea de cuál puede ser el problema o que estoy haciendo mal?

**Comment by eclipxe13** [comment]
Lo primero es leer la documentación oficial del SAT, las ligas están en el README:
https://github.com/phpcfdi/sat-ws-descarga-masiva#informaci%C3%B3n-oficial

Y leer la parte de la explicación de cómo funciona el servicio también del README:
https://github.com/phpcfdi/sat-ws-descarga-masiva#acerca-del-servicio-web-de-descarga-masiva-de-cfdi-y-retenciones

Sucede que entre presentar la solicitud, verificarla y descargarla hay que esperar a que el SAT responda, y eso puede ser cuestión de horas. En el ejemplo, las cosas se hacen secuenciales para ilustrar los métodos, en la práctica se debe hacer en diferentes tiempos.

Cuando se hizo `$verify = $service->verify($requestId);`, la variable `$verify` también contiene el estado de que se encuentra la solicitud. Debes consultar `$verify->getCodeRequest()` y `$verify->getStatusRequest()`.

Es importante leer la documentación para entender los estados que devuelve el servicio del SAT.

**Comment by avadnc** [comment]
Hola que tal? Yo obtuve el mismo error, luego me puse a buscar la documentación de la librería, pero tengo este problema, estas tres ligas me manda a página no encontrada.

Solicitud de descargas para CFDI y retenciones: https://www.sat.gob.mx/cs/Satellite?blobcol=urldata&blobkey=id&blobtable=MungoBlobs&blobwhere=1461173578576&ssbinary=true
Verificación de descargas de solicitudes exitosas: https://www.sat.gob.mx/cs/Satellite?blobcol=urldata&blobkey=id&blobtable=MungoBlobs&blobwhere=1461173578594&ssbinary=true
Descarga de solicitudes exitosas: https://www.sat.gob.mx/cs/Satellite?blobcol=urldata&blobkey=id&blobtable=MungoBlobs&blobwhere=1461173578561&ssbinary=true

**Comment by avadnc** [comment]
y tengo otro problema, si hice la solicitud, la cual me dio un UUID, pero cuando dumpeo el verify, en el status me da un 404.

```
object(PhpCfdi\SatWsDescargaMasiva\Services\Verify\VerifyResult)[33]
  private 'status' => 
    object(PhpCfdi\SatWsDescargaMasiva\Shared\StatusCode)[29]
      private 'code' => int 404
      private 'message' => string 'Error no controlado.' (length=20)
  private 'statusRequest' => 
    object(PhpCfdi\SatWsDescargaMasiva\Shared\StatusRequest)[30]
      private 'value' (PhpCfdi\SatWsDescargaMasiva\Shared\OpenEnum) => int 0
      private 'name' (PhpCfdi\SatWsDescargaMasiva\Shared\OpenEnum) => string 'Unknown' (length=7)
      private 'message' (PhpCfdi\SatWsDescargaMasiva\Shared\OpenEnum) => string '(valor del estado desconocido)' (length=30)
  private 'codeRequest' => 
    object(PhpCfdi\SatWsDescargaMasiva\Shared\CodeRequest)[46]
      private 'value' (PhpCfdi\SatWsDescargaMasiva\Shared\OpenEnum) => int 0
      private 'name' (PhpCfdi\SatWsDescargaMasiva\Shared\OpenEnum) => string 'Unknown' (length=7)
      private 'message' (PhpCfdi\SatWsDescargaMasiva\Shared\OpenEnum) => string '(valor del estado desconocido)' (length=30)
  private 'numberCfdis' => int 0
  private 'packagesIds' => 
    array (size=0)
      empty
```

**Comment by eclipxe13** [comment]
Nos ha pasado algunas veces, la documentación de los servicios del SAT solo dice que en estos casos lo vuelvas a intentar.

Nuestra interpretación es que ocurrió una excepción de su lado que no nos la dan a conocer.

**Comment by avadnc** [comment]
All Right :D Muchas Gracias y excelente trabajo!!
