### ISSUE TITLE
Error al procesar un certificado

### ISSUE THREAD

**Issue by crisscott** [phpcfdi/sat-ws-descarga-masiva#14]
Ocurre esta excepcion al ejecutar, sabras el porque?

Cannot open private key: error:23077074:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 cipherfinal

**Comment by eclipxe13** [comment]
Te refieres a un error al abrir la FIEL ?
La librería delega a [`phpcfdi/credentials`](https://github.com/phpcfdi/credentials#acerca-de-los-archivos-de-certificado-y-llave-privada) la apertura de la FIEL (certificado y llave privada).

Ahí se menciona que se pueden abrir llaves privadas en formato PKCS#8-DER, PKCS#8-PEM y PKCS#5-PEM, En este caso el error menciona PKCS#12.

Algunas preguntas:

¿Estás usando la llave privada tal como la entregó el SAT o la manipulaste?
Si fue manipulada, ¿qué comandos usaste?
Si no fue manipulada, ¿en qué fecha fue solicitada/emitida?

¿Podrías darnos todo el stack de la excepción?
¿Podrías darnos un ejemplo para reproducirlo?

**Comment by eclipxe13** [comment]
Se cierra este issue por falta de información
