### ISSUE TITLE
Crear herramienta CLI

### ISSUE THREAD

**Issue by eclipxe13** [phpcfdi/sat-ws-descarga-masiva#19]
Actualmente hay algunos scripts de muestra (dentro de `tests/Scripts`) que pueden ser utilizados para una ejecución de línea de comandos.

Lo mejor sería separar esta lógica en un proyecto independiente de primer nivel.

**Comment by eclipxe13** [comment]
En el PR #31 se eliminan los scripts... la herramienta `phpcfdi/sat-ws-descarga-masiva-cli` está en desarrollo y no se creará para la versión `0.3` pero sí para la `0.4`.

**Comment by AndreyPootMay** [comment]
@eclipxe13 se puede cerrar este issue?
