### ISSUE TITLE
Problemas al leer metadata con caracteres inesperados

### ISSUE THREAD

**Issue by eclipxe13** [phpcfdi/sat-ws-descarga-masiva#23]
El archivo de metadata retornado por el SAT contiene diversos campos, algunos de ellos son tomados directamente del archivo de CFDI.

Particularmente los campos `NombreEmisor` y `NombreReceptor` son expuestos tal y como fueron escritos en el CFDI. Y las reglas para estos campos, según el Anexo 20 son simplemente `[^|]{1,254}` (cualquier caracter que no sea `| (pipe)`, de 1 a 254 veces).

Esto lleva a que existan casos como: `<Receptor Nombre="&quot;Patito SA&#xD;&quot;">`, que es traducido a `"Patito SA<CR>"`.

Al momento en que este registro es exportado en el Metadata por el servicio web del SAT, se retorna una línea que está incompleta porque se parte en dos a causa del `<LF>` intermedio:

```text
UUID~...~AAA010101AAA~"Patito SA<LF>"~AAA010101AAA...<CR><LF>
```

Por alguna razón desconcida el SAT cambió el `<CR>` por un `<LF>`. El ejemplo anterior, al abrirlo en un editor de textos o importarlo como una hoja de cálculo aparece como dos líneas diferentes.

En términos prácticos, esto nos lleva a que los campos de `NombreEmisor` y `NombreReceptor` pueden contener caracteres de control, como `~`, `\~`, `<CR>`, `<LF>` y `"`, que provocarán una lectura defectuosa de la información.

Por lo anterior, el lector de Metadata, también interpreta dos líneas separadas de información, y por su misma naturaleza tolerante, dos líneas con errores de datos, la primera incompleta, y la segunda errónea.

Nota: El ejemplo anterior es un extracción de información de un caso totalmente real, y que aunque es poco común, todos estamos expuestos. Gracias al usuario `@TheSpectro` que nos compartió información suficiente en el canal de Discord para poder detectar el problema.

**Comment by cruzcraul** [comment]
@eclipxe13 ¿podemos tener acceso a un archivo csv con esas inconsistencias para poder realizar pruebas?

**Comment by eclipxe13** [comment]
No, contiene información confidencial.
Pero voy a generar uno y lo subo.

**Comment by eclipxe13** [comment]
Archivo de muestra: [sample.txt](https://github.com/phpcfdi/sat-ws-descarga-masiva/files/4957068/sample.txt)

**Comment by eclipxe13** [comment]
Sigo pensando en el problema y al menos encuentro dos características importantes:

* Las comillas no se están usando para delimitar entradas textuales, existen porque estaban desde el origen, por lo tanto es posible que actualmente `"Empresa Equis"` sea leída como `Empresa Foo` (sin comillas).

* Las líneas de los archivos terminan en `<CR><LF>`, lo que se encontró fue un `<LF>` intermedio, no hay que descartar que también podría existir un `<CR>` intermedio.

Considerando esto, y para no entorpecer al `SplFileObject`, podríamos implementar un *preprocesador*, que normalice el contenido del archivo aplicando estos dos cambios, incluso podría ocurrir que lleguemos a encontrar más casos que requieran más trabajo del *preprocesador*.

Alguna opinión antes de seguir esta estrategia y fabricar la clase `SatCsvMetadataPreprocesor` ?

**Comment by eclipxe13** [comment]
Estoy intentando hacer la reparación pero en el proceso me surgió la duda siguiente:

Esta cuestión de que los archivos de metadata terminan en `<CR><LF>` es reciente, o siempre se han escrito de esta forma.

¿Podría alguien con un archivo de metadata viejo (lo más que pueda) confirmarme si es esto cierto?

**Comment by eclipxe13** [comment]
Ya tengo 2 confirmaciones de que archivos con Metadata obtenidos en 2019 abril y mayo, contienen `EOL = <CR><LF>`. Gracias.

**Comment by eclipxe13** [comment]
Existen algunas suposiciones/dudas con respecto al archivo de texto de metadata:

- ¿Qué hace con el pipe?, se puede poner el pipe como `&#007C;`
- ¿Qué hace con la virgulilla `~`?, ¿la pone como `\~` si se llega a encontrar?
- ¿Porqué hizo la traducción de `<CR>` a `<LF>`?, el caracter que contenía el XML era `&#xD;`
- ¿Los `EOL` son siempre `<CR><LF>`?

Lamentablemente para poder contestar todas estas preguntas se necesitan a) CFDI con estos casos y b) la descarga de metadata consumiendo el servicio del SAT. No conozco a nadie que me quiera prestar sus CSD para hacer estas pruebas, cancelar los CFDI y luego que nos de su FIEL para poder consumir el servicio y descargar el metadata.
