### ISSUE TITLE
Consumo de webservice para CFDI de Retención

### ISSUE THREAD

**Issue by TheSpectroMx** [phpcfdi/sat-ws-descarga-masiva#29]
Buena tarde @eclipxe13.

Creo que hace falta consumir el webservice para obtener los CFDI de retenciones. Las URL's cambian entre ambos servicios:

**CFDI**
Autenticación: 
https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/Autenticacion/Autenticacion.svc
Solicitud:
https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/SolicitaDescargaService.svc
Verificación: 
https://cfdidescargamasivasolicitud.clouda.sat.gob.mx/VerificaSolicitudDescargaService.svc
Descarga: 
https://cfdidescargamasiva.clouda.sat.gob.mx/DescargaMasivaService.svc

**Retenciones**
Autenticación:
https://retendescargamasivasolicitud.clouda.sat.gob.mx/Autenticacion/Autenticacion.svc
Solicitud: 
https://retendescargamasivasolicitud.clouda.sat.gob.mx/SolicitaDescargaService.svc
Verificación:
https://retendescargamasivasolicitud.clouda.sat.gob.mx/VerificaSolicitudDescargaService.svc
Descarga: 
https://retendescargamasiva.clouda.sat.gob.mx/DescargaMasivaService.svc

**Comment by eclipxe13** [comment]
Imnplementado en https://github.com/phpcfdi/sat-ws-descarga-masiva/releases/tag/v0.4.0

**Comment by emilioHayes** [comment]
Saben si son las mismas URL para el SOAPAction ?
Dentro del projecto, vienen estas url (SOAPAction) pero, son las mismas para las URL de retenciones ?
Y si no, donde encuentro estas URL ? 
Otra duda que me surge es, en la documentacion del SAT te brindan las URL de los WS, pero no te brindan las URL del SOAPAction, entonces de donde las sacaron inicialmente ?

**Comment by eclipxe13** [comment]
Las URL listadas en este issue están en el documento *"Web service: URL's"* al que puedes acceder desde:

https://www.sat.gob.mx/consultas/42968/consulta-y-recuperacion-de-comprobantes-(nuevo)
https://www.sat.gob.mx/cs/Satellite?blobcol=urldata&blobkey=id&blobtable=MungoBlobs&blobwhere=1579314716425&ssbinary=true

Las `SOAPAction` están documentadas en los manuales respectivos (solicitud, verificación y descarga).

Para implementar la parte de retenciones solo apuntamos a las nuevas direcciones y ejecutamos pruebas, y funcionó.

**Comment by emilioHayes** [comment]
Gracias por tu respuesta, entonces las SOAPAction para las retenciones son las mismas? 
Uso las mismas URL de SOAPAction para los WS de retenciones e intento realizar descargas de retenciones y la parte de autenticación y solicitud funcionan bien, pero en el momento de la verificación no pasa, regresa "No se ha podido verificar la solicitud" y entiendo que esta parte se puede deber a que el servicio no esta funcionando, pero no se si se deba a esto o no estoy realizando el consumo correctamente.

**Comment by eclipxe13** [comment]
Creo que es el servicio del SAT, para obtener soporte de la comunidad (especialmente útil en estos temas) te recomiendo unirte al canal de discord de la comunidad de phpCfdi en <https://discord.gg/aFGYXvX>.
