### ISSUE TITLE
Hacer consulta de webservice sobre un RFC especifico

### ISSUE THREAD

**Issue by TheSpectroMx** [phpcfdi/sat-ws-descarga-masiva#30]
Esta bien sabido que el consumo del webservice trae como resultado todos los comprobantes Emitidos y/o Recibidos del periodo consultado. Pero ¿podría hacerse la consulta filtrando por RFC en especifico? El mismo caso para Metadata.

En el caso de emitidos traer solo los resultados de un RFC receptor o viceversa.

**Comment by eclipxe13** [comment]
Dado que no hay información oficial del servicio de consulta, ¿tienes tú alguna fuente o documento para saber cómo implementarlo?

**Comment by TheSpectroMx** [comment]
Supongo que quedaría algo así:

<des:solicitud FechaFinal="${end}" FechaInicial="${start}" ${rfcKey}="${rfc}" RfcReceptor="${filtro}" RfcSolicitante="${rfc}" TipoSolicitud="${requestTypeValue}"></des:solicitud>

Obvio las variantes son:

${rfcKey}="${rfc}" RfcReceptor="${filtro}"
RfcEmisor="${filtro}" RfcReceptor="${rfc}"

La información oficial existe en la documentación de Solicitud, existe lo siguiente:

`**Nota:** Aun cuando los parámetros de entrada RfcEmisor y RfcReceptor son opcionales, se requiere por lo menos uno de los dos.`

**Comment by eclipxe13** [comment]
Implementado en https://github.com/phpcfdi/sat-ws-descarga-masiva/releases/tag/v0.4.0
