### ISSUE TITLE
Error al verificar el estatus de la descarga

### ISSUE THREAD

**Issue by g3ck0** [phpcfdi/sat-ws-descarga-masiva#38]
no puedo generar una descarga valida, quiero decir, al momento de verificar que este lista la descarga, siempre me arroja el Estatus 5 (No se encontró la información: Indica que no generó paquetes por falta de información.), pero estoy usando un RFC valido y un periodo en el que se que genero facturas, una FIEL valida (real, no usuario de pruebas).

mando la fecha inicia, fecha final, tipo de descarga (ya intente con metadatos y cfdi) y el rfc, pero solo me regresa ese error, cualquier ayuda se agradeceria.

**Comment by TheSpectroMx** [comment]
Hola g3ck0 seria interesante ver como estas implementando el código ya que te puedo asegurar que la librería funciona. Te invito a entrar a la comunidad de discord https://discord.gg/hqhCMxC y checar de forma más rapida el error que comentas

**Comment by TheSpectroMx** [comment]
Ahora bien, volviendo a leer puede que el error de tu consulta sea problema de implementación, me recuerda a un problema de implementación que se resolvió ayer y si no mal recuerdo daba el mismo mensaje de error.

```php
$request = QueryParameters::create(
    DateTimePeriod::createFromValues('2019-01-13 00:00:00', '2019-01-13 23:59:59'),
    DownloadType::issued(), // FACTURAS EMITIDAS POR EL CONTRIBUYENTE QUE INICIO SESION EN EL WS
    RequestType::metadata(), // TIPO DE CONSULTA PUEDE SER METADATA / CFDI
    'MAG041126GT8' // INGRESAR SOLO SI QUEREMOS UN RFC EN ESPECIFICO ENTRE LAS ' '
);
);```

**Comment by eclipxe13** [comment]
Excelente respuesta @TheSpectroMx !
Tal vez si @g3ck0 nos comparte cómo está armando su solicitud `QueryParameters::create(...)` podamos saber si es esa la situación o si el problema es diferente.

**Comment by g3ck0** [comment]
> Ahora bien, volviendo a leer puede que el error de tu consulta sea problema de implementación, me recuerda a un problema de implementación que se resolvió ayer y si no mal recuerdo daba el mismo mensaje de error.
> 
> ```
> $request = QueryParameters::create(
>     DateTimePeriod::createFromValues('2019-01-13 00:00:00', '2019-01-13 23:59:59'),
>     DownloadType::issued(), // FACTURAS EMITIDAS POR EL CONTRIBUYENTE QUE INICIO SESION EN EL WS
>     RequestType::metadata(), // TIPO DE CONSULTA PUEDE SER METADATA / CFDI
>     'MAG041126GT8' // INGRESAR SOLO SI QUEREMOS UN RFC EN ESPECIFICO ENTRE LAS ' '
> );
> ```
> 
> En DownloadType::issued() - Estas solicitando las facturas emitidas
> Si en 'MAG041126GT8' estas colocando el RFC del que esta iniciando sesión en el WS (al que pertenece la FIEL). Lo que estas solicitando es las facturas emitidas para el mismo RFC (autofactura). Intenta dejando esa parte vacía (sin colocar un RFC) para que solicites todas las facturas emitidas o coloca el RFC de un cliente que sepas que se le expidió factura en el periodo solicitado te aseguro que de esa forma la consulta funcionara sin problemas.

muchas gracias por las respuestas, y tuviste razon @TheSpectroMx , mi problema era que estaba poniendo el mismo RFC en el request, ya pude hacer la solicitud y descarga de los comprobantes.

Gracias otra vez.
