### ISSUE TITLE
Descargar por UUID

### ISSUE THREAD

**Issue by fernas** [phpcfdi/sat-ws-descarga-masiva#41]
¿Es posible crear una consulta por UUID?

**Comment by TheSpectroMx** [comment]
Hola @fernas, por este metodo que es webservice no es posible hacer filtro por UUID. Podrías utilizar https://github.com/phpcfdi/cfdi-sat-scraper ques un scrap de la página del SAT y ahí si podrías descargar por UUID. 

Te invito a pasar a la comunidad de discord https://discord.gg/hqhCMxC para estar en tiempo real.
