### ISSUE TITLE
"Error no controlado" en cualquier petición

### ISSUE THREAD

**Issue by gmizaelmtzhdz** [phpcfdi/sat-ws-descarga-masiva#42]
Hola, 
Haciendo pruebas con la librería en su versión "0.4.2", siempre me retorna el mensaje "Error no controlado".
¿A alguien más le está pasando esto?
Intenté hacer pruebas en local y en un servidor  (por aquello del posible bloqueo por IP) y el resultado siempre fue el mismo.

**Comment by TheSpectroMx** [comment]
En que proceso te regresa este mensaje?

**Comment by gmizaelmtzhdz** [comment]
Hola @TheSpectroMx , el error de "Error no controlado", lo retorna cuando hago la solicitud de descarga (específicamente en: **$query->getStatus()->getMessage()**), comparto fragmentos de código que estoy utilizando: 


```
#EMISOR
$request = QueryParameters::create(
  DateTimePeriod::createFromValues($fecha_inicio, $fecha_fin),
  DownloadType::issued(), //'issued' => 'RfcEmisor', 'received' => 'RfcReceptor',
  RequestType::cfdi()
);
```

```
#RECEPTOR
$request = QueryParameters::create(
  DateTimePeriod::createFromValues($fecha_inicio, $fecha_fin),
  DownloadType::received(), //'issued' => 'RfcEmisor', 'received' => 'RfcReceptor',
  RequestType::cfdi()
);
```



```
#PRESENTAR LA CONSULTA
$query = $this->service->query($request);
// verificar que el proceso de consulta fue correcto
if (! $query->getStatus()->isAccepted()) {
   $this->log=$this->log. "Fallo al presentar la consulta: {$query->getStatus()->getMessage()}";
}
else
{
  // el identificador de la consulta está en $query->getRequestId()
  $this->log=$this->log. "Se generó la solicitud {$query->getRequestId()}";
  $request_id = $query->getRequestId();
}
```



Nota:

- $fecha_inicio y $fecha_fin tienen formato: "YYYY-MM-DD HH:MM:SS"
- $this->service está declarado así: 
```
$webClient = new GuzzleWebClient();
// creación del objeto encargado de crear las solicitudes firmadas usando una FIEL
$requestBuilder = new FielRequestBuilder($fiel);
// Creación del servicio
$this->service = new Service($requestBuilder, $webClient);

```

**Comment by TheSpectroMx** [comment]
Hola de nuevo @gmizaelmtzhdz veo cosas interesantes, de entrada te recomiendo que hagas las pruebas con metadata ya que esta no tiene limitantes como lo tienen CFDI, en este último solo vas a poder solicitar un máximo de dos veces el mismo periodo, despues te arrojara el mensaje de "agotado de por vida".

Tengo la duda de si te regresa un id de solicitud hecha. Recuerda que es un proceso asíncrono, por lo cual antes de intentar descargar deberías de confirmar que la solicitud tenga el estado de "Terminado".

¿Haz intentado con los ejemplos de uso? Donde tengo la duda es porque pones:

```php
$this->service = new Service($requestBuilder, $webClient);
```
en lugar de:
```php
service = new Service($requestBuilder, $webClient);
```
como viene en el ejemplo de uso. Si quieres para que sea más rápida la interacción te invito a formar parte de la comunidad en Discord https://discord.gg/hqhCMxC

Quedo al pendiente de tu respuesta.

**Comment by gmizaelmtzhdz** [comment]
Originalmente había metido la abstracción de consultas (como vienen en el README.md) en una clase, por eso utilizaba el $this->service (lo tenia declarado como una variable de instancia). Pero viendo el mensaje que me retorna, empecé a hacer pruebas solo con los ejemplos que vienen en el README.md sin ningún otro código, y obtuve lo siguiente: 

- Utilizando el ejemplo "https://github.com/phpcfdi/sat-ws-descarga-masiva#realizar-una-consulta" (con rango de fecha de los últimos 3 meses), me retorna: 
  - `Fallo al presentar la consulta: Error no controlado` 
  -  Y si utilizo el método `$query->getStatus()->getCode()` me retorna: 404
  - Aún así veo que si me retorna un ID de solicitud si mando llamar a "$query->getRequestId()"
- Utilizando el ID de solicitud de la petición anterior y utilizando este fragmento de código "https://github.com/phpcfdi/sat-ws-descarga-masiva#verificar-una-consulta", me retorna: 
  - Fallo al verificar la consulta xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx: No se encontro la informacion
  - Y si utilizo el método `$query->getStatus()->getCode()` me retorna: 5004


Obtengo el mismo resultado  si pongo "RequestType::metadata()" o  "RequestType::cfdi()"

**Nota**: hice pruebas la primer semana de Diciembre 2021, con exactamente el mismo código y mismo RFC y si me funcionó, pero desde el Miércoles/Jueves que retomé las pruebas, ahora me está dando este error, probé con diferentes RFC's y el resultado sigue siendo el mismo. 

Hice una búsqueda en internet sobre la documentación del webservice, y dí con éste PDF (https://www.sat.gob.mx/cs/Satellite?blobcol=urldata&blobkey=id&blobtable=MungoBlobs&blobwhere=1579314716402&ssbinary=true), veo que la descripción de los errores es el siguiente: 

- 404 - Error no Controlado - Error genérico, en caso de presentarse realizar nuevamente la petición y si persiste el error levantar un RMA.
- 5004 - No viene info. en el PDF sobre el detalle de este código de resultado. 


¿Será que por la temporada los servidores del SAT están caídos?

**Comment by gmizaelmtzhdz** [comment]
@TheSpectroMx volví a hacer pruebas el domingo 26 de Diciembre con la misma versión ("0.4.2"), con exactamente los mismos fragmentos de código que vienen en el README.md y con los mismos RFC's, sin cambiar absolutamente nada y ahora si me retorna un ID de solicitud válido ya sea  "RequestType::metadata()" o "RequestType::cfdi()". Y puedo descargar las facturas o los metadatos sin problema. 

**Conclusión**: La única conclusión lógica hasta ahorita es que los servidores del SAT estaban caídos o al menos no funcionando en la forma en la que deberían (como vienen plasmado en la documentación).

**Comment by TheSpectroMx** [comment]
@gmizaelmtzhdz me alegro al saber que ya te funciona, es posible como bien lo mencionas que el problema haya sido del lado del SAT, ya que las ultimas semanas ha estado intermitente el servicio de descarga masiva por webservice. Solo como comentario, cuando te arroja "No se encontró la información" es porque en teoría no hay CFDI en el periodo indicado. Si estas de acuerdo, podrías cerrar este issue, ya que por lo que comentas no es propio de la librería. Saludos.
