### ISSUE TITLE
Conteo de Cfdi

### ISSUE THREAD

**Issue by yashiroiori** [phpcfdi/sat-ws-descarga-masiva#43]
Que tal, el paquete es muy bueno

Mi pregunta es sobre cómo poder hacer para saber solo la cantidad de cfdi que tenga la consulta?? o hay algo para poder saberlo para no afectar el punto de solicitar 2 veces el mismo xml

A que se refiere este punto "No existe limitante en cuanto al número de solicitudes siempre que no se descargue en más de dos ocasiones un XML."?? eso es que el xml se encuentre dentro de las consultas?? que si consulto 2022-01-01 al 2022-01-02 y luego  hago otra consulta con otro rango de fechas 2021-12-31 al 2022-01-10 se cuentan todos los xml en este caso "2022-01-01 y 2022-01-02" como dobles?? y/o también cuenta que se haga dos veces la misma consulta?? o solo cuenta cuando se pide descargar el XML?? pero siendo solo metadatos no afecta en nada??

Esto es para poder determinar si son mas 200,000 poder hacer una manera para separar el rango de fechas en varias consultas y evitar que de alguna manera se pidan fechas repetidas nuevamente, ya sea que no encontró resultados, o falló por algún motivo la consulta, etc.

**Comment by TheSpectroMx** [comment]
Hola @yashiroiori la única forma rápida de saber cuantos CFDIs tiene un periodo es por medio de una consulta Metadata, ya que soporta hasta 1 millon de "registros" (CFDIs). Asi las cosas si un periodo tiene más de 200 mil podrias acortarlo para que no exceda el limite de una consulta de tipo CFDI.

Ahora bien la limitante en la consulta CFDI se refiere basicamente a que no puedes solicitar más de 2 veces el mismo periodo. Por ejemplo puedes hacer :

1er Consulta - 01-01-2021 al 31-03-2021
2da Consulta - 25-01-2021 al 28-02-2021
3er Consulta - 30-01-2021 al 15-02-2021

En esas 3 consultas tendrías repetidos sin problemas los CFDIs del 30 de enero al 15 de febrero. Ahora bien si intentas descargar 3 veces esas 3 consultas, te devolverá el mensaje de "agotado de por vida". Espero que haya aclarado tus dudas, quedo al pendiente.

**Comment by yashiroiori** [comment]
> 
Si había pensado hacer una consulta solo Metadata

Si hago una consulta solo Metadata duplicando varias veces el periodo sigue afectando para la descarga xml?? o solo afecta si se duplica solicitando con xml??

Quiero entender bien esto para poder integrar en los sistemas una precarga de información de los clientes pero como los clientes no saben cuantos tienen por periodos se tendría que hacer un conteo antes de solicitar la descarga de los XML

**Comment by celli33** [comment]
Hola @yashiroiori, en metadata no hay límite para las veces que puedes descargar el mismo periodo. Así que no, no afecta a la descarga de xml. Agregaría a los periodos que comenta @TheSpectroMx que los periodos son distintos al variar solo un segundo esto es:

1. 01-01-2021 00:00:00 al 31-03-202 23:59:59 es distinta al periodo 01-01-2021 00:00:01 al 31-03-202 23:59:59. Tener esto en cuenta te puede ayudar por si llegas a exceder el límite de 3 consultas por periodo.

**Comment by TheSpectroMx** [comment]
En Metadata no esta esa limitante hasta el momento, ahí puedes consultar el mismo periodo las veces que quieras. Los tipos de consulta son independientes en cuestión de las limitaciones. La mayoria ocupa la consulta Metadata para saber cuantos CFDIs hay en ese periodo y el estado de la solicitud en el momento en el que se solicita la consulta.

Un ejemplo de uso seria al dia de hoy hacer una consulta tipo CFDI  y Metadata del 01-01-2022 al 12-01-2022. Vas a tener todos los CFDIs del 1ero al 12 de enero (consulta CFDI) y vas a poder conocer su respectivo estado de vigente/cancelado (consulta Metadata) al día de hoy hasta las 19:40hrs.

Pero si por alguna razón cancelan CFDIs en lo que resta del día, tendrías que hacer una consulta nueva Metadata con el mismo periodo (01-01-2022 al 12-01-2022) para saber el estado actual de los CFDIs, ya no seria necesario descargar los CFDIs. Al menos que por alguna razon no coincida el numero de CFDIs entre ambas descargas Metadata.

Si gustas para tener una interacción más rápida te invito a formar parte de la comunidad más bonita, PHPeros, te dejo el link de discord https://discord.gg/Tr3dze9M

Si no de cualquier forma andamos al pendiente de tus comentarios.

**Comment by yashiroiori** [comment]
> En Metadata no esta esa limitante hasta el momento, ahí puedes consultar el mismo periodo las veces que quieras. Los tipos de consulta son independientes en cuestión de las limitaciones. La mayoria ocupa la consulta Metadata para saber cuantos CFDIs hay en ese periodo y el estado de la solicitud en el momento en el que se solicita la consulta.
> 
> Un ejemplo de uso seria al dia de hoy hacer una consulta tipo CFDI y Metadata del 01-01-2022 al 12-01-2022. Vas a tener todos los CFDIs del 1ero al 12 de enero (consulta CFDI) y vas a poder conocer su respectivo estado de vigente/cancelado (consulta Metadata) al día de hoy hasta las 19:40hrs.
> 
> Pero si por alguna razón cancelan CFDIs en lo que resta del día, tendrías que hacer una consulta nueva Metadata con el mismo periodo (01-01-2022 al 12-01-2022) para saber el estado actual de los CFDIs, ya no seria necesario descargar los CFDIs. Al menos que por alguna razon no coincida el numero de CFDIs entre ambas descargas Metadata.
> 
> Si gustas para tener una interacción más rápida te invito a formar parte de la comunidad más bonita, PHPeros, te dejo el link de discord https://discord.gg/Tr3dze9M
> 
> Si no de cualquier forma andamos al pendiente de tus comentarios.

Excelente muchísimas gracias 👍
