### ISSUE TITLE
¿Se puede saber si un CFDI está cancelado?

### ISSUE THREAD

**Issue by gmizaelmtzhdz** [phpcfdi/sat-ws-descarga-masiva#46]
Hola,

Tengo una duda con el Webservice del SAT ¿se puede saber si un CFDI está cancelado?, hasta ahorita la única solución que le he encontrado es una combinación:

- Webservice del SAT para la extracción masiva de los CFDI's vigentes
- Web Scraping para obtener las canceladas (semi-automatizada ya que requiere la captura del captcha)

¿Habrá alguna otra forma automatizada de saber si los CFDI's están cancelados?

**Comment by EmmanuelJCS** [comment]
Podrías, descargar los XML's, luego leer los datos y hacer una petición al SAT en su webservice para ver el estado del CFDI, es lo que de forma rápida se me ocurre, si necesitas la URL del WebService es la siguiente: https://consultaqr.facturaelectronica.sat.gob.mx/ConsultaCFDIService.svc
Saludos

**Comment by eclipxe13** [comment]
> Web Scraping para obtener las canceladas (semi-automatizada ya que requiere la captura del captcha)

Estás hablando de [phpcfdi/cfdi-sat-scraper](https://github.com/phpcfdi/cfdi-sat-scraper)
Si usas el servicio externo de Anti-Captcha y con eso se automatiza.
Además puedes usar la implementación por FIEL y ya no requiere captcha.
Y se puede solicitar solo los cancelados en un periodo de tiempo, eso lo agiliza bastante.

> ¿Habrá alguna otra forma automatizada de saber si los CFDI's están cancelados?

Sí, aunque es uno por uno. Mira el proyecto [phpcfdi/sat-estado-cfdi](https://github.com/phpcfdi/sat-estado-cfdi)
