### ISSUE TITLE
Error por parte del SAT?

### ISSUE THREAD

**Issue by hectorbarranca** [phpcfdi/sat-ws-descarga-masiva#65]
Hola, disculpa ahorita les está fallando el servicio por parte del SAT?

Desde aproximadamente el día 6 o 7 de junio del 2024 estoy notando que al verificar la petición el estado de la misma se queda en 1 (Aceptada) pero no pasa de ahí, no se si les esté pasando lo mismo, como todo parece fluir bien creo que es por parte del SAT pero agradecería mucho si me comentaran si están pasando por lo mismo.

Saludos y muchas gracias

**Comment by MiguelAngelMP10** [comment]
Que tal @hectorbarranca es correcto el servicio de descarga masiva del SAT se encuentra con intermitencias te invitamos a unirte a la comuninidad por medio de discord https://discord.gg/aFGYXvX, te esperados

**Comment by hectorbarranca** [comment]
Muchas gracias por tu confirmación, también ayer parece que se reestableció y veo que ya se están descargando todos los pendientes, muchas gracias nuevamente
